---
title: "Biologia_Systemów_Gillespie_gen"
author: "Zofia Sikorska"
format: html
editor: visual
---

```{r}
library("deSolve")
```

# Symulacja modelu ekspresji genu

```{r}
stoch_gene <- function(k_r, gamma_r, k_p, gamma_p, m0, p0, t_max){   
  times <- 0   
  m_vec  <- m0  
  p_vec  <- p0   
  
  t_now <- 0
  
  while(t_now < t_max){     
    
    m <- tail(m_vec, 1)     
    p <- tail(p_vec, 1) 
    
    v1 <- k_r     
    v2 <- gamma_r * m     
    v3 <- k_p    * m     
    v4 <- gamma_p * p          
    h <- v1 + v2 + v3 + v4     
    
    if(h == 0) break 
    
    r1 <- runif(1); 
    r2 <- runif(1)     
    tau <- -log(r1) / h
    
    cum_v <- cumsum(c(v1, v2, v3, v4)) / h
    j <- which(r2 <= cum_v)[1]
    
    t_now <- t_now + tau
    
    if (j == 1) m_new <- m + 1     
    else if (j == 2) m_new <- m - 1     
    else m_new <- m  
    
    if (j == 3) p_new <- p + 1     
    else if (j == 4) p_new <- p - 1     
    else p_new <- p  
    
    times <- c(times, t_now)     
    m_vec  <- c(m_vec,  m_new)     
    p_vec  <- c(p_vec,  p_new)   }      
  
  return(list(times = times, m = m_vec, p = p_vec)) } 

t_max <- 8*3600 
gene_1 <- stoch_gene(k_r= 0.01, gamma_r = 0.1, k_p = 1, gamma_p = 0.002, m0= 0, p0 = 0, t_max)    
gene_2 <- stoch_gene(k_r = 0.1, gamma_r = 0.1, k_p = 0.1, gamma_p = 0.002, m0= 0, p0 = 0, t_max)  
```

## 1. Wyrysowanie trajektorii na jednym wykresie

```{r}
plot(gene_1$times, gene_1$m,       
     type = "l", col = "orange",       
     xlab = "Czas", ylab = "Liczba cząstek",      
     main = "Gene k=0.01",      
     ylim = c(0, max(c(gene_1$m, gene_1$p)))) 
lines(gene_1$times, gene_1$p, col = "darkgreen")  
legend("topright",         
       legend = c("mRNA", "Protein"),
       col = c("orange", "darkgreen"),         
       lty = 1)
```

```{r}
plot(gene_2$times, gene_2$m,       
     type = "l", col = "orange",       
     xlab = "Czas", ylab = "Liczba cząstek",      
     main = "Gene k=0.1",      
     ylim = c(0, max(c(gene_2$m, gene_2$p)))) 
lines(gene_2$times, gene_2$p, col = "darkgreen")  
legend("topright",         
       legend = c("mRNA", "Protein"),     
       col = c("orange", "darkgreen"),lty = 1)
```

## 2. Wyrysowanie stoch i det na jednym wykresie

```{r}

gene_det <- function(t, y, parameters){   
  k_r <- parameters[1]   
  k_p <- parameters[2]   
  gamma_r <- parameters[3]   
  gamma_p <- parameters[4]      
  
  m <- y[1]   
  p <- y[2]      
  
  dm <- k_r - gamma_r*m   
  dp <- k_p*m - gamma_p*p      
  
  list(c(dm, dp)) }
```

```{r}
parameters_gene_1 <- c(k_r = 0.01, kp = 1, gamma_r = 0.1, gamma_p = 0.002) 
parameters_gene_2 <- c(k_r = 0.1, kp = 0.1, gamma_r = 0.1, gamma_p = 0.002) 

inits_gen <- c(m=0, p=0) 

times <- seq(0, 8*3600, by = 10)  

gen1 <- as.data.frame(ode(   y = inits_gen,   times = times,   func = gene_det,   parms = parameters_gene_1 )) 

gen2 <- as.data.frame(ode(   y = inits_gen,   times = times,   func = gene_det,   parms = parameters_gene_2 ))
```

### k=0.01

```{r}
plot(gene_1$times, gene_1$m,       
     type = "l",col = "orange",
     xlab = "Czas", ylab = "Liczba cząstek",      
     main = "Porównanie stochastyczne-deterministyczne",      
     ylim = c(0, max(c(gene_1$p, gen1$p ))),lwd = 2) 
lines(gene_1$times, gene_1$p, col = "darkgreen", lwd = 2) 
lines(gen1$time, gen1$m, col = "blue", lty = 2, lwd = 2) 
lines(gen1$time, gen1$p, col = "red", lty = 2, lwd = 2) 
legend("topright",         
       legend = c("mRNA (stoch)", "Białko (stoch)", "mRNA (det)", "Białko (det)"),        col = c( "orange", "darkgreen","blue", "red"),         lty = c(1, 1, 2, 2),        lwd = 2)
```

### k =0.1

```{r}
plot(gene_2$times, gene_2$m,       
     type = "l",col = "orange",
     xlab = "Czas", ylab = "Liczba cząstek",      
     main = "Porównanie stochastyczne-deterministyczne",      
     ylim = c(0, max(c(gene_2$p, gen2$p ))),lwd = 2) 
lines(gene_2$times, gene_2$p, col = "darkgreen", lwd = 2) 
lines(gen2$time, gen2$m, col = "blue", lty = 2, lwd = 2) 
lines(gen2$time, gen2$p, col = "red", lty = 2, lwd = 2) 
legend("topright",         
       legend = c("mRNA (stoch)", "Białko (stoch)", "mRNA (det)", "Białko (det)"),  
       col = c("orange", "darkgreen", "blue", "red"),         
       lty = c(1, 1, 2, 2), lwd = 2)
```
